[tool.black]
exclude = '''
    migrations
    | venv
'''

[tool.isort]
profile = "black"
known_django = "django"
sections = "FUTURE,STDLIB,DJANGO,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
skip = '''
    migrations
    venv
'''

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "gacha_api.settings"
addopts = "--reuse-db"
