name: Test on push

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/checkout@v2
        with:
          python-version: 3.9
      - name: Setup env for backend
        run: |
          cp example.env.local .env.local
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --user -r requirements.txt -r requirements-dev.txt
      #   run: pytest
      - name: flake8
        run: flake8 .
      - name: black
        run: black --check .
      - name: isort
        run: isort --check .
